rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby
  - rbx
  - rbx-2.0
  - ree
notifications:
  email:
    - durran@gmail.com
    - arunagw@gmail.com
    - cgriego@gmail.com
    - nick@deadorange.com
    - paul@codingfrontier.com
    - bj.schaefer@gmail.com
