language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - jruby
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
env: JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"
matrix:
  allow_failures:
    - rvm: jruby-head
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#mongoid"
services:
  - mongodb
