rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby
  - jruby-head
env:
  - JRUBY_OPTS="--1.9 --server -Xinvokedynamic.constants=true"
  - RUBY_HEAP_FREE_MIN=100000
  - RUBY_HEAP_MIN_SLOTS=600000
  - RUBY_GC_MALLOC_LIMIT=60000000
branches:
  except:
    - moped-integration
