test:
  sessions:
    default:
      database: mongoid_test
      hosts:
        - <%=ENV["MONGOID_SPEC_HOST"]%>:<%=ENV["MONGOID_SPEC_PORT"]%>
      options:
        user: "mongoid-test-user"
        password: "password"
        read:
          mode: primary
  options:
    include_root_in_json: false
    include_type_for_serialization: false
    preload_models: false
    scope_overwrite_exception: false
    raise_not_found_error: true
    use_activesupport_time_zone: true
    use_utc: false
